Repository woowa-techcamp-2022/android-repo-05, pull requests merged in 2022-07, with the labels that each got.

#9 MainActivity Tab Menu 구현
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_repo_05/customviews/MainTabButton.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/MainActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/ProfileActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/SearchActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/IssueFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/NotificationFragment.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/MainViewModel.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_issueclosed.xml
  app/src/main/res/drawable/ic_issueopen.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_mail.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_searchbold.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_users.xml
  app/src/main/res/drawable/ic_variant10.xml
  app/src/main/res/drawable/ic_variant16.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/menu/home_toolbar_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feat

#12 Github OAuth 로그인 구현 완료
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_repo_05/data/datastore/DataStoreExt.kt
  app/src/main/java/com/example/android_repo_05/data/model/LoginResponse.kt
  app/src/main/java/com/example/android_repo_05/data/model/ResponseState.kt
  app/src/main/java/com/example/android_repo_05/repositories/GithubApiRepository.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/LoginViewModel.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/MainViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat

#19 프로필 화면 UI 작업 완료
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/android_repo_05/ui/fragments/IssueFragment.kt
  app/src/main/res/drawable/ic_star_outline.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/issue_filtering_spinner.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ui

#20 Github Users Api를 사용하는 로직 구현
  app/src/main/java/com/example/android_repo_05/data/model/UserInfo.kt
  app/src/main/java/com/example/android_repo_05/others/Constants.kt
  app/src/main/java/com/example/android_repo_05/others/Utils.kt
  app/src/main/java/com/example/android_repo_05/repositories/GithubApiRepository.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApiInstance.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/ProfileActivity.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/AppViewModelFactory.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/LoginViewModelFactory.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/UserInfoViewModel.kt
Labels: feat

#29 데이터 바인딩을 통해 유저 정보 화면에 표시
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/android_repo_05/adapters/AppBindingAdapter.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/ProfileActivity.kt
  app/src/main/res/layout/activity_profile.xml
Labels: feat

#30 [FEAT] Issue Fragment 구현
  app/build.gradle
  app/src/main/java/com/example/android_repo_05/adapters/AppBindingAdapter.kt
  app/src/main/java/com/example/android_repo_05/adapters/IssuePagingAdapter.kt
  app/src/main/java/com/example/android_repo_05/adapters/IssueSpinnerAdapter.kt
  app/src/main/java/com/example/android_repo_05/customviews/IssueFilteringSpinner.kt
  app/src/main/java/com/example/android_repo_05/data/model/IssueResponse.kt
  app/src/main/java/com/example/android_repo_05/others/Utils.kt
  app/src/main/java/com/example/android_repo_05/paging/IssuePagingSource.kt
  app/src/main/java/com/example/android_repo_05/repositories/IssueRepository.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/IssueFragment.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/AppViewModelFactory.kt
  app/src/main/java/com/example/android_repo_05/viewmodels/IssueViewModel.kt
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/item_issue.xml
  app/src/main/res/layout/item_issue_filter_head.xml
  app/src/main/res/menu/issue_filter_popup_menu.xml
Labels: feat

#41 [UI] SearchActivity UI 구성
  app/src/main/res/drawable/bg_search_language_color.xml
  app/src/main/res/drawable/bg_search_tf.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ui

#51 [FEAT] SearchActivity Paging 구현
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_repo_05/adapters/RepositoryPagingAdapter.kt
  app/src/main/java/com/example/android_repo_05/data/models/RepositoryModel.kt
  app/src/main/java/com/example/android_repo_05/data/models/RepositoryResponse.kt
  app/src/main/java/com/example/android_repo_05/data/repositories/ProfileImageRepository.kt
  app/src/main/java/com/example/android_repo_05/data/repositories/RepositoryRepository.kt
  app/src/main/java/com/example/android_repo_05/others/Constants.kt
  app/src/main/java/com/example/android_repo_05/paging/IssuePagingSource.kt
  app/src/main/java/com/example/android_repo_05/paging/RepositoryPagingSource.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/MainActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/SearchActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/AppViewModelFactory.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/RepositoryViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_repository.xml
  app/src/main/res/layout/item_search.xml
Labels: feat

#55 Swipe로 Notification 읽음 처리 구현 완료
  app/src/main/java/com/example/android_repo_05/adapters/NotificationAdapter.kt
  app/src/main/java/com/example/android_repo_05/adapters/helpers/NotificationItemHelperCallback.kt
  app/src/main/java/com/example/android_repo_05/data/models/notification/NotificationModel.kt
  app/src/main/java/com/example/android_repo_05/data/repositories/NotificationRepository.kt
  app/src/main/java/com/example/android_repo_05/others/Utils.kt
  app/src/main/java/com/example/android_repo_05/paging/NotificationPagingSource.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/NotificationFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/AppViewModelFactory.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/NotificationViewModel.kt
Labels: feat

#58 [FEAT] SearchActivity 기능 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/android_repo_05/adapters/AppBindingAdapter.kt
  app/src/main/java/com/example/android_repo_05/others/Utils.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/SearchActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/IssueFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/RepositoryViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_repository.xml
Labels: feat

#65 프로필 화면과 알림 리스트 화면 데이터 Loading, Success, Fail 처리 및 알림 리스트 Refresh
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/android_repo_05/adapters/PagingLoadStateAdapter.kt
  app/src/main/java/com/example/android_repo_05/data/models/UserModel.kt
  app/src/main/java/com/example/android_repo_05/paging/NotificationPagingSource.kt
  app/src/main/java/com/example/android_repo_05/retrofit/AuthInterceptor.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/ProfileActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/NotificationFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/UserViewModel.kt
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_load_state.xml
  app/src/main/res/values/strings.xml
Labels: feat

#66 [FEAT] Issue Spinner, Search CustomView 추가
  .idea/misc.xml
  app/src/main/java/com/example/android_repo_05/adapters/IssueSpinnerAdapter.kt
  app/src/main/java/com/example/android_repo_05/customviews/IssueFilteringSpinner.kt
  app/src/main/java/com/example/android_repo_05/customviews/SearchTextInputEditText.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/SearchActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/IssueFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/IssueViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/RepositoryViewModel.kt
  app/src/main/res/drawable/bg_issue_unselected_filter.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/item_issue_filter.xml
Labels: feat, done

#69 UX를 위한 여러 작업을 완료
  .idea/misc.xml
  app/src/main/java/com/example/android_repo_05/adapters/IssueSpinnerAdapter.kt
  app/src/main/java/com/example/android_repo_05/adapters/PagingLoadStateAdapter.kt
  app/src/main/java/com/example/android_repo_05/customviews/IssueFilteringSpinner.kt
  app/src/main/java/com/example/android_repo_05/data/models/notification/CommentModel.kt
  app/src/main/java/com/example/android_repo_05/data/models/notification/RepositoryModel.kt
  app/src/main/java/com/example/android_repo_05/data/models/notification/SubjectModel.kt
  app/src/main/java/com/example/android_repo_05/others/Constants.kt
  app/src/main/java/com/example/android_repo_05/paging/IssuePagingSource.kt
  app/src/main/java/com/example/android_repo_05/paging/NotificationPagingSource.kt
  app/src/main/java/com/example/android_repo_05/paging/RepositoryPagingSource.kt
  app/src/main/java/com/example/android_repo_05/retrofit/GithubApi.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/ProfileActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/SearchActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/fragments/IssueFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/IssueViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/RepositoryViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_issue.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_load_state.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat

#70 네트워크가 연결되지 않았을 때 데이터를 로드할 경우 앱이 죽는 현상 수정
  app/src/main/java/com/example/android_repo_05/data/repositories/NotificationRepository.kt
  app/src/main/java/com/example/android_repo_05/data/repositories/ProfileImageRepository.kt
  app/src/main/java/com/example/android_repo_05/data/repositories/TokenRepository.kt
  app/src/main/java/com/example/android_repo_05/data/repositories/UserRepository.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/MainViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/UserViewModel.kt
  app/src/main/res/layout/activity_profile.xml
Labels: bug

#71 [REFACTOR] Glide 성능 향상 및 MainActivity, ProfileActivity 데이터 바인딩 적용
  app/build.gradle
  app/src/main/java/com/example/android_repo_05/adapters/AppBindingAdapter.kt
  app/src/main/java/com/example/android_repo_05/base/CustomApplication.kt
  app/src/main/java/com/example/android_repo_05/others/GlideModule.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/MainActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/activities/ProfileActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
Labels: refactoring

#76 [REFACTOR] #72 - 서치 디바운싱 기능 적용 방식 수정
  app/src/main/java/com/example/android_repo_05/ui/activities/SearchActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/viewmodels/RepositoryViewModel.kt
Labels: refactoring

#80 Hilt를 통한 DI 적용
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/android_repo_05/CustomApplication.kt
  app/src/main/java/com/example/android_repo_05/data/login/TokenRepository.kt
  app/src/main/java/com/example/android_repo_05/data/login/TokenRepositoryImpl.kt
  app/src/main/java/com/example/android_repo_05/data/main/ProfileImageRepository.kt
  app/src/main/java/com/example/android_repo_05/data/main/ProfileImageRepositoryImpl.kt
  app/src/main/java/com/example/android_repo_05/data/main/issue/IssueRepository.kt
  app/src/main/java/com/example/android_repo_05/data/main/issue/IssueRepositoryImpl.kt
  app/src/main/java/com/example/android_repo_05/data/main/issue/paging/IssuePagingSource.kt
  app/src/main/java/com/example/android_repo_05/data/main/notification/NotificationRepository.kt
  app/src/main/java/com/example/android_repo_05/data/main/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/example/android_repo_05/data/main/notification/paging/NotificationPagingSource.kt
  app/src/main/java/com/example/android_repo_05/data/network/GithubApiInstance.kt
  app/src/main/java/com/example/android_repo_05/data/network/GithubApiService.kt
  app/src/main/java/com/example/android_repo_05/data/profile/UserRepository.kt
  app/src/main/java/com/example/android_repo_05/data/profile/UserRepositoryImpl.kt
  app/src/main/java/com/example/android_repo_05/data/search/RepositoryRepository.kt
  app/src/main/java/com/example/android_repo_05/data/search/RepositoryRepositoryImpl.kt
  app/src/main/java/com/example/android_repo_05/data/search/paging/RepositoryPagingSource.kt
  app/src/main/java/com/example/android_repo_05/di/RepositoryModule.kt
  app/src/main/java/com/example/android_repo_05/di/ServiceModule.kt
  app/src/main/java/com/example/android_repo_05/ui/common/AppViewModelFactory.kt
  app/src/main/java/com/example/android_repo_05/ui/login/LoginActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/login/TokenViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/main/MainActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/main/MainViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/main/issue/IssueFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/main/issue/IssueViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/main/notification/NotificationFragment.kt
  app/src/main/java/com/example/android_repo_05/ui/main/notification/NotificationViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/profile/ProfileActivity.kt
  app/src/main/java/com/example/android_repo_05/ui/profile/UserViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/search/RepositoryViewModel.kt
  app/src/main/java/com/example/android_repo_05/ui/search/SearchActivity.kt
  build.gradle
Labels: refactoring

#81 딥링크 코드 개선
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_repo_05/ui/login/LoginActivity.kt
  build.gradle
Labels: bug
